### ISSUE TITLE
As a Code Chica, I want to have access to the original content on the new website so that I can refer back to class material and access it easily.

### ISSUE THREAD

**Issue by xlgmokha** [CodeChica/codechica.github.io#1]
Attachments for each class:

Lesson 1

* [ ] [List of HTML Tags](https://docs.google.com/document/d/1cUOJd1J00x3JQKG3dZczJhrAcHKEsGJB/edit?usp=sharing&ouid=102529568764296321619&rtpof=true&sd=true)
* [ ] [HTML Slide Deck](https://drive.google.com/file/d/1DMBo6YACbbj0vmfq1ryqFHg27V6h1qTO/view)
* [ ] [HTML Cheat Sheet](http://www.simplehtmlguide.com/cheatsheet.php)
* [ ] [Color Names](https://www.w3schools.com/colors/colors_names.asp)
* [ ] [HTML Styles](https://www.w3schools.com/html/html_styles.asp)
* [ ] [Accessibility](https://www.w3schools.com/html/html_accessibility.asp)
* [ ] [Introduction to HTML || Your First Web Page || Part 1](https://youtu.be/BvJYXl2ywUE)
* [ ] [Introduction to HTML || Basic HTML Elements || Part 2](https://youtu.be/PypMN-yui4Y)
* [ ] [Introduction to HTML || Advanced HTML Elements || Part 3](https://youtu.be/1rbo_HHt5nw)
* [ ] [Introduction to HTML || Links and Inputs || Part 4](https://youtu.be/bFvjE4ZRtSE)
* [ ] [HTML in 5 minutes | Webpage Tutorial | Code in 5](https://youtu.be/4K4QhIAfGKY)
* [ ] [Containers](https://www.w3schools.com/w3css/w3css_containers.asp)
* [ ] [Divs](https://www.w3schools.com/tags/tag_div.ASP)
* [ ] [Buttons](https://www.w3schools.com/w3css/w3css_buttons.asp)
* [ ] [Video - Linking CSS to HTML](https://youtu.be/3Sn7nQxoitM)
* [ ] [HTML Table Tags](https://drive.google.com/file/d/1ACfj_JKY0oDazwOVkFIBdIdchBOZ7dgq/view)
* [ ] [Adding Images](https://drive.google.com/file/d/13-W44rz4SzkKjfsAb0bSv2-zrHPOrXED/view)
* [ ] [File Paths](https://drive.google.com/file/d/1z5l0IGH7FEflpHDyU4hSuTdGx2nZ4nQF/view)

Lesson 2

* [ ] [Wireframe Homepage Example](https://drive.google.com/file/d/1C3W4ioAmJW4x8gID7TuVdfW6cvQpQd2C/view)
* [ ] [Wireframe Sitemap Example](https://drive.google.com/file/d/1CS1jqHnVE7LZmR4gBFxyvdQoEHDybeT-/view)
* [ ] [Figma](https://www.figma.com/wireframe-tool/)

**Comment by xlgmokha** [comment]
@arianestier Are you able to upload the original content to the issue description?

**Comment by LadySubrosa** [comment]
I'm in!

**Comment by arianestier** [comment]
Added some links! Not sure if I did that correctly... I may have just edited your comment instead of the issue description.

**Comment by LadySubrosa** [comment]
I want to plan to hit the first 3 in this check list (though the link for "Class 1" doesn't go anywhere, so starting with the next items on the list)

**Comment by xlgmokha** [comment]
"Class 1" was an example that I left last night to get us going. I deleted it now that we have some links. Thanks @arianestier!

**Comment by LadySubrosa** [comment]
@arianestier do you know if that first google doc is a copy of this page from w3schools? https://www.w3schools.com/TAGS/default.ASP would we want to link out to these resources in the HTML guide or create our own copy within the code chica website?

**Comment by LadySubrosa** [comment]
I plan to add those first 3 to this page https://codechica.ca/plus-plus/guides/html.html

(I also think we should add the whole footer from these ++ pages onto every page in the website. Having it on the homepage would be great! I'll make sure that's part of this work)

**Comment by LadySubrosa** [comment]
Sorry for all the comments, but i now realize that is a guide for ++ students. Any reason not to combine forces here? Or maybe would we want to use the same page and have a "Beginner" section and a ++ section? Or make a new Beginner focus guide/url that is a child page of the Code Chica section of the website?

**Comment by xlgmokha** [comment]
> would we want to link out to these resources in the HTML guide or create our own copy within the code chica website?

If we choose to link to HTML guides can we avoid W3Schools and maybe favor [MDN](https://developer.mozilla.org/en-US/) instead?

**Comment by xlgmokha** [comment]
> Any reason not to combine forces here?

Originally I thought that we might use the same guides for both courses but then I recall concern being raised about how the target audience for the content might be different. e.g. the HTML guide for the first course might focus on the structure of an HTML element etc and the HTML guide for ++ might focus more on different types of tags or ways of describing a document using semantic markup etc. I could go either way.


> Or maybe would we want to use the same page and have a "Beginner" section and a ++ section?

That would be way easier. Maybe we can start with this?

> Or make a new Beginner focus guide/url that is a child page of the Code Chica section of the website?

I don't have a strong opinion on this but I think the current structure of the pages makes it easier to have HTML guides in separate pages for each class. I don't know if we'll end up adding a third class or not so it *might* be something we'll need to re-organize in the future. For now... I think we probably don't need to overthink it and start with whatever makes sense. I trust your judgement.

**Comment by LadySubrosa** [comment]
> > would we want to link out to these resources in the HTML guide or create our own copy within the code chica website?
> 
> If we choose to link to HTML guides can we avoid W3Schools and maybe favor [MDN](https://developer.mozilla.org/en-US/) instead?

Good call out! I wonder if the MDN may be a little overwhelming for a teen/beginner. Maybe we can call out the tags we want to include in our guide that are important to the class, then link out to the bigger MDN guide for chicas ready to learn more/dive deeper?

**Comment by xlgmokha** [comment]
> Maybe we can call out the tags we want to include in our guide that are important to the class, then link out to the bigger MDN guide for chicas ready to learn more/dive deeper?

I like hosting our own content because it also gives the students a chance to edit and refine that content. Linking out where it makes sense is great as supplemental info but I don't want to rely on it for our primary content because we don't own it and can't tweak it specifically for our audience. https://codechica.ca/plus-plus/guides/html.html was my quick attempt to showcase how we could include our own YT videos and content that is focused and slimmed down. Hopping out to external links and back can be ... confusing.

edit: I'd also love to have someone re-record some of those videos because the ones I recorded are kind of low quality and they're mostly for placement only. I hope that people look at the content and think to themselves "I could record a better version of this". Then I'd love for them to do so and replace the videos that we have.
